version: 1.0.{build}.0

services:
  - mssql2012sp1

environment:
  ContosoUniversity.ConnectionString: Server=(local)\SQL2012SP1;Database=ContosoUniversity;User ID=sa;Password=Password12!
  ContosoUniversity.Tests.ConnectionString: Server=(local)\SQL2012SP1;Database=ContosoUniversity_Tests;User ID=sa;Password=Password12!

branches:
  only:
    - master

build_script:
- cmd: .\build.bat ci "%APPVEYOR_BUILD_VERSION%"

test: off

artifacts:
- path: .\build\packages\**
  name: NuGet

deploy_script:
- choco install octopustools
- octo create-release --project "CI/CD Example" --version %APPVEYOR_BUILD_VERSION% --server https://headspring-od.southcentralus.cloudapp.azure.com --apiKey API-TX1JGNZHPF6KRBJNESS6465QYHA --packageversion %APPVEYOR_BUILD_VERSION% --deployto "PM Development" --ignoreSslErrors

